default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: crisalix
  username: root
  password:

development:
  <<: *default

test:
  <<: *default
  database: crisalix_test

production:
  <<: *default